# Generated by Django 3.2 on 2021-06-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='updated_at',
            new_name='upload_to',
        ),
    ]
